### ISSUE TITLE
Java Version Incompatability 

### ISSUE THREAD

**Issue by SumanthReddyKaliki** [OscarRodriguezPrieto/ProgQuery#14]
**Currently I'm using JDK 8 and our source code only be compiled using java 8, so I can't use higher versions of java**

**But the ProgQuery is complied using higher version of Java (Java 13). Because of that I'm getting an error**

`java.lang.UnsupportedClassVersionError: ProgQueryPlugin has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0.
`
Based on my understanding, the only way to fix this

1. either I upgrade to java 13 (which is not possible in my case )

2. Or recompile your ProgQuery code for lower version of Java (Java 8).

So I would appreciate if you could share the binaries/classfiles for Java 8 or tell me how to recompile your code using Java 8 so that I can generate the jar files on my own. Sorry for the confusion, I'm new to Java.

**Comment by OscarRodriguezPrieto** [comment]
Hi @SumanthReddyKaliki 

I update the last 1.1.5 Release with the binaries compiled with Java 8.
Please, if you get any other error, tell me.
