### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/neo4j/graphdb/Label

### ISSUE THREAD

**Issue by BenTang2018** [OscarRodriguezPrieto/ProgQuery#16]
After entering the command according to the instructions in the document, the system prompts me with this error. Do I need to install other packages to use ProgQuery?
![T()@TCRJ9CV@K_8TR2CPD`W](https://user-images.githubusercontent.com/75242867/103147085-6165ff00-478c-11eb-9f4b-2e30ec173fbf.png)

**Comment by fakhrinail** [comment]
May I know how did you solve this issue?
