### ISSUE TITLE
How to extract control-flow and basic data-flow graphs?

### ISSUE THREAD

**Issue by nashid** [OscarRodriguezPrieto/ProgQuery#24]
This is a fantastic project and the paper was a great read! I will be interested to use this tool to perform some program analysis tasks.

I need to extract control-flow and basic data-flow graphs i.e. def-use for intraprocedural analysis. My intention is to feed the enclosing function body of the java source code.

I am wondering whether this tool is a good fit to extract control-flow and data-flow edges? Also, can I extract control-flow and data-flow graphs to dot or JSON files?

I would be happy to modify and add functionality as needed.

Any help is appreciated!

**Comment by OscarRodriguezPrieto** [comment]
Hi Nashid

Thank you very much for your flattering comments about ProgQuery!

ProgQuery was mainly designed to provide semantic representations of source code.
These semantic representations (Control flow graphs, data-flow graphs, method invocation graphs, etc) are stored in a Neo4j database for posterior querying (you can use Cypher, Gremlin, the Java Driver, etc.) and extract useful information to build your dataset (or make any other kind of search, analysis, etc.).

The semantic representations are just Neo4j edges connecting different syntactic nodes in the Abstract Syntax Tree (a structural view of the program). For example, an ATTR_DEF node (representing an attribute defined in some class) will be connected to all the expression nodes in which the attribute is used (by means of one semantic edge type called USED_BY) or modified (by means of MODIFIED_BY edges). For a complete description of all the different kinds of semantic edges that ProgQuery supports, please see the technical report in http://www.reflection.uniovi.es/bigcode/download/2020/ieee-access/tr.pdf

You already have made a fork, so feel free to extend and adapt the functionality of ProgQuery as you want and you can keep asking doubts if you feel the need.
